apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 087605768816.dkr.ecr.ap-northeast-2.amazonaws.com/alarm-app
  newName: 087605768816.dkr.ecr.ap-northeast-2.amazonaws.com/alarm-app
  newTag: 22f61a03
- name: 087605768816.dkr.ecr.ap-northeast-2.amazonaws.com/backend-app
  newName: 087605768816.dkr.ecr.ap-northeast-2.amazonaws.com/backend-app
  newTag: 27f940e5
- name: 087605768816.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app
  newName: 087605768816.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app
  newTag: 9815ac3a
resources:
- ../../base
