apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alarm-app
  template:
    metadata:
      labels:
        app: alarm-app
    spec:
      containers:
        - name: alarm-app
          image: 087605768816.dkr.ecr.ap-northeast-2.amazonaws.com/alarm-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: jdbcUrl
              value: jdbc:mariadb://crawling-server.c4y9vm1irfhh.ap-northeast-2.rds.amazonaws.com:3306/classmoa
            - name: username
              valueFrom:
                secretKeyRef:
                  name: rds-db-password
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: rds-db-password
                  key: password
            - name: org.mariadb.jdbc.Driver
              value: org.mariadb.jdbc.Driver
            - name: gmail
              valueFrom:
                secretKeyRef:
                  name: mail-password
                  key: gmail
            - name: gmailPassword
              valueFrom:
                secretKeyRef:
                  name: mail-password
                  key: gmailPassword
---
apiVersion: v1
kind: Service
metadata:
  name: alarm-svc
  annotations:
  # alb.ingress.kubernetes.io/healthcheck-path: "/services/all"
spec:
  selector:
    app: alarm-app
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30002
