apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
        - name: front-app
          image: 087605768816.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app:2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: default
  annotations:
  # alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: front-app
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30000