apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alarm-app
  template:
    metadata:
      labels:
        app: alarm-app
    spec:
      containers:
        - name: alarm-app
          image: $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/alarm-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: alarm-svc
  annotations:
  # alb.ingress.kubernetes.io/healthcheck-path: "/services/all"
spec:
  selector:
    app: alarm-app
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30002
