apiVersion: apps/v1
kind: Deployment
metadata:
  name: classmoa-backend-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classmoa-backend-app
  template:
    metadata:
      labels:
        app: classmoa-backend-app
    spec:
      containers:
        - name: classmoa-backend-app
          image: 087605768816.dkr.ecr.ap-northeast-2.amazonaws.com/classmoa:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: back-container
---
apiVersion: v1
kind: Service
metadata:
  name: classmoa-backend-app
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/contents/aws"
spec:
  selector:
    app: classmoa-backend-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP